site_name: SentinelIQ SDK
site_description: Utility classes for building SentinelIQ analyzers and responders
site_url: https://killsearch.github.io/sentineliqsdk/
repo_url: https://github.com/killsearch/sentineliqsdk
repo_name: killsearch/sentineliqsdk

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/github

nav:
  - Architecture:
    - Overview: architecture/overview.md
  - Development:
    - Contributing: development/contributing.md
    - Documentation Style Guide: development/documentation-style-guide.md
  - Examples:
    - Malware Analysis: examples/malware-analysis.md
    - Responders: examples/responders.md
    - Threat Intelligence: examples/threat-intelligence.md
  - Getting Started:
    - First Analyzer: getting-started/first-analyzer.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Guides:
    - Agent Guide: guides/guide.md
    - HTTPX Client Pattern: guides/httpx-client.md
  - Home: index.md
  - Modules:
    - Analyzers:
      - AbuseIPDB: modulos/analyzers/abuseipdb.md
      - AnyRun: modulos/analyzers/anyrun.md
      - AutoFocus: modulos/analyzers/autofocus.md
      - Axur: modulos/analyzers/axur.md
      - Censys: modulos/analyzers/censys.md
      - ChainAbuse: modulos/analyzers/chainabuse.md
      - CIRCL Hashlookup: modulos/analyzers/circl_hashlookup.md
      - CIRCL Passive DNS: modulos/analyzers/circl_passivedns.md
      - CIRCL PassiveSSL: modulos/analyzers/circl_passivessl.md
      - CIRCL Vulnerability Lookup: modulos/analyzers/circl_vulnerability_lookup.md
      - ClamAV: modulos/analyzers/clamav.md
      - Cluster25: modulos/analyzers/cluster25.md
      - CrowdSec: modulos/analyzers/crowdsec.md
      - CrowdStrike Falcon: modulos/analyzers/crowdstrike_falcon.md
      - Crt.sh: modulos/analyzers/crtsh.md
      - Cuckoo Sandbox: modulos/analyzers/cuckoo.md
      - CyberChef: modulos/analyzers/cyberchef.md
      - CyberCrime Tracker: modulos/analyzers/cybercrime_tracker.md
      - MCAP: modulos/analyzers/mcap.md
      - Shodan: modulos/analyzers/shodan.md
    - Clients:
      - Axur Client: modulos/clients/axur.md
      - Cluster25 Client: modulos/clients/cluster25.md
      - CrowdSec Client: modulos/clients/crowdsec.md
      - Shodan Client: modulos/clients/shodan.md
    - Consumers:
      - Kafka Consumer: modulos/consumers/kafka_consumer.md
    - Detectors:
      - ASN: modulos/detectors/asn.md
      - CIDR: modulos/detectors/cidr.md
      - CVE: modulos/detectors/cve.md
      - Domain: modulos/detectors/domain.md
      - FQDN: modulos/detectors/fqdn.md
      - Hash: modulos/detectors/hash.md
      - IP: modulos/detectors/ip.md
      - IP Port: modulos/detectors/ip_port.md
      - MAC: modulos/detectors/mac.md
      - Mail: modulos/detectors/mail.md
      - Registry: modulos/detectors/registry.md
      - URI Path: modulos/detectors/uri_path.md
      - URL: modulos/detectors/url.md
      - User-Agent: modulos/detectors/user-agent.md
    - Pipelines:
      - Security Pipeline: modulos/pipelines/security_pipeline.md
    - Producers:
      - Kafka Producer: modulos/producers/kafka_producer.md
    - Responders:
      - Gmail SMTP: modulos/responders/gmail_smtp.md
      - Kafka REST: modulos/responders/kafka_rest.md
      - Outlook SMTP: modulos/responders/outlook_smtp.md
      - RabbitMQ HTTP: modulos/responders/rabbitmq_http.md
      - Webhook: modulos/responders/webhook.md
  - Reference:
    - Analyzer: reference/api/analyzer.md
    - Extractor: reference/api/extractor.md
    - Models: reference/api/models.md
    - Responder: reference/api/responder.md
    - Worker: reference/api/worker.md
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md
    - FAQ: troubleshooting/faq.md
  - Tutorials:
    - Building Analyzers: tutorials/building-analyzers.md
    - Building Responders: tutorials/building-responders.md
    - File Processing: tutorials/file-processing.md

plugins:
  - search
  - mermaid2
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            separate_signature: true
            show_root_heading: true
            show_signature_annotations: true
            filters:
              - '!^_'

markdown_extensions:
  - admonition
  - codehilite
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/killsearch/sentineliqsdk
