site_name: SentinelIQ SDK
site_description: Utility classes for building SentinelIQ analyzers and responders
site_url: https://killsearch.github.io/sentineliqsdk/
repo_url: https://github.com/killsearch/sentineliqsdk
repo_name: killsearch/sentineliqsdk

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - First Analyzer: getting-started/first-analyzer.md
  - Tutorials:
    - Building Analyzers: tutorials/building-analyzers.md
    - Building Responders: tutorials/building-responders.md
    - File Processing: tutorials/file-processing.md
  - Examples:
    - Threat Intelligence: examples/threat-intelligence.md
    - Malware Analysis: examples/malware-analysis.md
    - Responders: examples/responders.md
  - Guides:
    - Agent Guide: guides/guide.md
  - Reference:
    - Worker: reference/api/worker.md
    - Analyzer: reference/api/analyzer.md
    - Responder: reference/api/responder.md
    - Extractor: reference/api/extractor.md
    - Models: reference/api/models.md
  - Architecture:
    - Overview: architecture/overview.md
  - Development:
    - Contributing: development/contributing.md
  - Troubleshooting:
    - Common Issues: troubleshooting/common-issues.md
    - FAQ: troubleshooting/faq.md

plugins:
  - search
  - mermaid2
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            separate_signature: true
            show_root_heading: true
            show_signature_annotations: true
            filters:
              - '!^_'

markdown_extensions:
  - admonition
  - codehilite
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/killsearch/sentineliqsdk
